global:
  env: dta
  automated: true
  spec:
    project: platform-dta
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/mojtabaimani/idp-kubernetes.git
      targetRevision: 1-pg-configuration
    values:
      repoURL: https://github.com/mojtabaimani/idp-kubernetes.git
      targetRevision: 1-pg-configuration

applications:
  # A Kustomize application
  hello:
    enabled: false
    path: values/hello/overlays/dta

  raw:
    enabled: false
    path: apps/raw/dta

  cnpg-database:
    enabled: false
    namespace: cloudnative-pg
    path: apps/cnpg-database/dta


helmCharts:
  teams-namespaces:
    enabled: false
    namespace: default

  backstage:
    enabled: false


  keycloak:
    enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 18.4.0

  sealed-secrets:
    enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.8.5
    chart: sealed-secrets

  airflow:
    enabled: false
    repoURL: https://airflow.apache.org
    targetRevision: 1.12.0
    chart: airflow

  nginx-ingress:
    enabled: false
    repoURL: ghcr.io/nginxinc/charts
    targetRevision: 1.1.2
    chart: nginx-ingress

  kube-prometheus-stack:
    enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    targetRevision: 56.7.0
    chart: kube-prometheus-stack

  loki:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 0.78.2
    chart: loki-distributed

  promtail:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 6.15.5
    chart: promtail

  harbor:
    enabled: false
    repoURL: https://helm.goharbor.io
    namespace: harbor
    targetRevision: 1.14.0
    chart: harbor

  cert-manager:
    enabled: false
    repoURL: https://charts.jetstack.io
    namespace: cert-manager
    targetRevision: 1.14.2
    chart: cert-manager

  actions-runner-controller:
    enabled: false
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    namespace: actions-runner-system
    targetRevision: 0.22.0
    chart: actions-runner-controller
    syncWave: 0

  actions-runner:
    enabled: false
    repoURL: https://github.com/mojtabaimani/idp-kubernetes.git
    namespace: actions-runner-system
    syncWave: 1

  gitea:
    enabled: false
    repoURL: https://dl.gitea.io/charts
    namespace: gitea
    targetRevision: 10.1.1
    chart: gitea

  postgresql:
    enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    namespace: postgresql
    targetRevision: 14.1.0
    chart: postgresql

  cloudnative-pg:
    enabled: false
    repoURL: https://cloudnative-pg.github.io/charts
    namespace: cloudnative-pg
    targetRevision: 0.20.1
    chart: cloudnative-pg
