global:
  env: dta
  automated: true
  spec:
    project: platform-dta
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/mojtabaimani/idp-kubernetes.git
      targetRevision: 1-pg-configuration
    values:
      repoURL: https://github.com/mojtabaimani/idp-kubernetes.git
      targetRevision: 1-pg-configuration

applications:

  # helm-guestbook:
  #   enabled: true

helmCharts:
  teams-namespaces:
    enabled: true
    namespace: default

  backstage:
    enabled: true


  keycloak:
    enabled: true
    repoURL: registry-1.docker.io/bitnamicharts
    chart: keycloak
    targetRevision: 16.0.3

  sealed-secrets:
    enabled: true
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.11.0
    chart: sealed-secrets

  airflow:
    enabled: true
    repoURL: https://airflow.apache.org
    targetRevision: 1.10.0
    chart: airflow

  nginx-ingress:
    enabled: true
    repoURL: ghcr.io/nginxinc/charts
    targetRevision: 0.18.0
    chart: nginx-ingress

  kube-prometheus-stack:
    enabled: true
    repoURL: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    targetRevision: 48.3.3
    chart: kube-prometheus-stack

  loki:
    enabled: true
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 0.71.1
    chart: loki-distributed

  promtail:
    enabled: true
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 6.14.1
    chart: promtail

  harbor:
    enabled: true
    repoURL: https://helm.goharbor.io
    namespace: harbor
    targetRevision: 1.12.4
    chart: harbor

  cert-manager:
    enabled: true
    repoURL: https://charts.jetstack.io
    namespace: cert-manager
    targetRevision: 1.12.3
    chart: cert-manager

  actions-runner-controller:
    enabled: true
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    namespace: actions-runner-system
    targetRevision: 0.22.0
    chart: actions-runner-controller
    syncWave: 0

  actions-runner:
    enabled: true
    repoURL: https://github.com/mojtabaimani/idp-kubernetes.git
    namespace: actions-runner-system
    syncWave: 1

  gitea:
    enabled: true
    repoURL: https://dl.gitea.io/charts
    namespace: gitea
    targetRevision: 9.5.0
    chart: gitea

  postgresql:
    enabled: true
    repoURL: https://charts.bitnami.com/bitnami
    namespace: postgresql
    targetRevision: 14.1.0
    chart: postgresql

  cloudnative-pg:
    enabled: true
    repoURL: https://cloudnative-pg.github.io/charts
    namespace: cloudnative-pg
    targetRevision: 0.20.1
    chart: cloudnative-pg

  configuration:
    enabled: true
