global:
  env: dta

applications:
  # A Kustomize application
  hello:
    enabled: true
    path: values/hello/overlays/dta

  configuration:
    enabled: true
    path: apps/configuration/dta


helmCharts:
  keycloak:
    enabled: true

  helm-guestbook:
    enabled: false
    name: helm-guestbook
    namespace: guestbook

  sealed-secrets:
    enabled: true

  airflow:
    enabled: false

  nginx-ingress:
    enabled: true

  cert-manager:
    enabled: false

  actions-runner-controller:
    enabled: false

  actions-runner:
    enabled: false

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  harbor:
    enabled: false

  cert-manager:
    enabled: false

  actions-runner-controller:
    enabled: false

  actions-runner:
    enabled: false

  gitea:
    enabled: false

  postgresql:
    enabled: false

  backstage:
    enabled: true

  cloudnative-pg:
    enabled: true
