{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ template "helm-guestbook.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "helm-guestbook.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
{{- end }}
