persistence:
  enabled: true
service:
  type: LoadBalancer
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.127.0.0.1.nip.io
      path: /
      pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
