apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-database
  namespace: cloudnative-pg
spec:
  instances: 3

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  storage:
    size: 10Gi

  monitoring:
    enablePodMonitor: true
