{{- range .Values.cloudnativePgClusters }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  instances: {{ .postgresql.instances }}
  postgresql:
    version: {{ .postgresql.version }}
  users:
{{ toYaml .users | indent 4 }}
  databases:
{{ toYaml .databases | indent 4 }}
  storage:
    size: {{ .storage.size }}
    storageClassName: {{ .storage.storageClassName }}
  backup:
    enabled: {{ .backup.enabled }}
    schedule: {{ .backup.schedule }}
    keep: {{ .backup.keep }}
  recovery:
    enabled: {{ .recovery.enabled }}
---
{{- end }}
