{{- range .Values.cloudnativePgClusters }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  {{ .users[0].passwordSecret.key }}: {{ .secret.password | b64enc }}
---
{{- end }}
