configs:
  cm:
    timeout.reconciliation: 5s
  params:
    server.insecure: true
controller:
  metrics:
    enabled: true
server:
  insecure: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    ingressClassName: "nginx"
    hostname: argocd.127.0.0.1.nip.io
    paths:
      - /
    pathType: Prefix
    https: false
