{{- range $name, $app := .Values.helmCharts -}}
{{ if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default $name .name }} # Better to have the same names for different environment, then the config would be more similar to each others -{{ $.Values.global.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ default 0 .syncWave }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    team: platform
spec:
  project: {{ $.Values.global.spec.project }}
  sources:
  - repoURL:  {{ default $.Values.global.spec.source.repoURL .repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
    {{- if hasKey . "chart"}}
    chart: {{ .chart }}
    {{- else }}
    path: apps/{{ default $name .name }}
    {{- end }}
    helm:
{{- if fileExists (printf "$valuesRepo/values/%s/values-%s.yaml" (default $name .name) $.Values.global.env) }}
      valueFiles:
      - $valuesRepo/values/{{ default $name .name }}/values-{{ $.Values.global.env }}.yaml
{{- end }}
  - repoURL: {{ $.Values.global.spec.values.repoURL }}
    targetRevision: {{ default $.Values.global.spec.values.targetRevision .valuesTargetRevision }}
    ref: valuesRepo
  destination:
    namespace: {{ default $name .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if default $.Values.global.automated .automated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
{{- end }}
{{- end }}
