apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-database
  namespace: cloudnative-pg
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  # FIXME:
  enableSuperuserAccess: true
  superuserSecret:
    name: app-secret
